### PR TITLE
Implement Contacts #get method

### PR DESCRIPTION
**Pull request by cy-ken-goto**
```
ChatWork.api_key = "hoge"
puts ChatWork::Contacts.get()
```

http://developer.chatwork.com/ja/endpoint_contacts.html#GET-contacts

### CODE REVIEW

**Comment by asonas** [comment]
:sparkles:

**Comment by cy-ken-goto** [comment]
thx!!

**Comment by asonas** [comment]
@cy-ken-goto 
v0.2.0 released! :rocket: 
Thanks for your contribution!

https://rubygems.org/gems/chatwork/versions/0.2.0

**Comment by gotyoooo** [comment]
:+1:

**Pull request merged**
